# Generated by Django 4.0.5 on 2022-06-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='cv_cert',
            field=models.FileField(blank=True, null=True, upload_to='cv'),
        ),
    ]
